version: '3'

services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-root}
      MYSQL_USER: ${MYSQL_USER-foo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-bar}
      MYSQL_DATABASE: ${MYSQL_DATABASE-baz}
    image: mysql:${MYSQL_VERSION-8.0.32}
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro'
      - 'mysql:/var/lib/mysql'

  php:
    build:
      context: docker/php
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION-2.5}
        PHP_VERSION: ${PHP_VERSION-8.2.3}
        DEBUG: ${DEBUG-1}
    environment:
      COMPOSER_CACHE_DIR: '/composer/cache'
    depends_on:
      - mailhog
      - mysql
    ports:
      - '9000'
    volumes:
      - '.:/srv/app'
      - '${COMPOSER_CACHE_DIR-~/.cache/composer}:/composer/cache'
    user: ${UID-1000}:${GID-1000}

  web:
    environment:
      NGINX_HOST: ${NGINX_HOST-localhost}
      NGINX_ALIASES: ${NGINX_ALIASES-}
    depends_on:
      - php
    image: nginx:${NGINX_VERSION-1.23.3}-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.:/srv/app'
      - './docker/nginx/vhost.common.d:/etc/nginx/vhost.common.d'
      - './docker/nginx/templates:/etc/nginx/templates'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mysql:
