version: '3'

services:
  mariadb:
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD-root}
      MARIADB_USER: ${MARIADB_USER-foo}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD-bar}
      MARIADB_DATABASE: ${MARIADB_DATABASE-baz}
    image: mariadb:${MARIADB_VERSION-11.5.2}
    ports:
      - '3306:3306'
    volumes:
      - './docker/mariadb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro'
      - 'mariadb:/var/lib/mysql'

  php:
    build:
      context: docker/php
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION-2.8}
        PHP_VERSION: ${PHP_VERSION-8.3.13}
        DEBUG: ${DEBUG-1}
    environment:
      COMPOSER_CACHE_DIR: '/composer/cache'
    depends_on:
      - mailhog
      - mariadb
    ports:
      - '9000'
    volumes:
      - '.:/srv/app'
      - '${COMPOSER_CACHE_DIR-~/.cache/composer}:/composer/cache'
    user: ${UID-1000}:${GID-1000}

  web:
    environment:
      NGINX_HOST: ${NGINX_HOST-localhost}
      NGINX_ALIASES: ${NGINX_ALIASES-}
    depends_on:
      - php
    image: nginx:${NGINX_VERSION-1.27.2}-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.:/srv/app'
      - './docker/nginx/vhost.common.d:/etc/nginx/vhost.common.d'
      - './docker/nginx/templates:/etc/nginx/templates'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mariadb:
